sudo: required
services:
  - docker

before_install:
  - docker build -t kikidun/node.k -f Dockerfile.dev .

script:
  - docker run kikidun/node.k npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "node.k"
  env: "Nodek-env"
  bucket_name: "elasticbeanstalk-us-east-1-563748380420"
  bucket_path: "node.k"
  on:
    branch: master
  access_key_id: $AWS_Access_Key
  secret_access_key:
    secure: "$AWS_Secret_Key"
